import { useEffect } from "react";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gray-100 p-8">
      <div className="max-w-3xl mx-auto bg-white shadow-md rounded-lg p-6">
        <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
        <p className="mb-4 text-gray-700">
          Welcome to <strong>PopMitra</strong>! By using our application or
          website, you agree to these Terms of Service. Please read them
          carefully.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">
          1. Acceptance of Terms
        </h2>
        <p className="mb-4 text-gray-700">
          By accessing or using PopMitra, you agree to comply with and be bound
          by these Terms of Service. If you do not agree, please do not use our
          service.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">2. Use of Service</h2>
        <p className="mb-4 text-gray-700">
          PopMitra is a free tool that generates content (titles, descriptions,
          hashtags) using AI technology. You agree not to misuse the service or
          use it for illegal, harmful, or abusive purposes.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">3. AI Disclaimer</h2>
        <p className="mb-4 text-gray-700">
          Content generated by PopMitra is powered by Google&apos;s Gemini API.
          We do not guarantee the accuracy, completeness, or suitability of
          AI-generated content. You are solely responsible for reviewing and
          using the content appropriately.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">
          4. Intellectual Property
        </h2>
        <p className="mb-4 text-gray-700">
          The PopMitra name, logo, and design belong to us. You retain ownership
          of the text you input into the service. Generated outputs may be used
          freely, subject to Google&apos;s Gemini API policies.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">
          5. Limitation of Liability
        </h2>
        <p className="mb-4 text-gray-700">
          PopMitra is provided &quot;as is&quot; without warranties of any kind.
          We are not responsible for any damages, losses, or issues arising from
          the use of the service or reliance on AI-generated content.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">6. Changes to Terms</h2>
        <p className="mb-4 text-gray-700">
          We may update or modify these Terms from time to time. Continued use
          of PopMitra means you accept any changes.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">7. Governing Law</h2>
        <p className="mb-4 text-gray-700">
          These Terms are governed by the laws of <strong>Nepal</strong>.
        </p>

        <p className="mt-8 text-gray-600">
          If you have questions about these Terms, contact us at{" "}
          <a
            href="mailto:redcoder008@gmail.com"
            className="text-blue-500 underline"
          >
            redcoder008@gmail.com
          </a>
          .
        </p>

        <div className="mt-8">
          <a href="/" className="text-blue-500 underline hover:text-blue-700">
            Return to Home
          </a>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
